## 1. Create the Dataset

In [1]:
import numpy as np

# Define input (X) for XOR function
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)

# Define output (y) for XOR function
y = np.array([[0], [1], [1], [0]], dtype=np.float32)

print("Input (X):\n", X)
print("Output (y):\n", y)

Input (X):
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Output (y):
 [[0.]
 [1.]
 [1.]
 [0.]]


### Interpretation of Dataset Creation

The `X` array represents the two binary inputs for the XOR function, and the `y` array represents the corresponding binary output. This dataset covers all four possible combinations of inputs and their expected XOR results.

## 2. Build an MLP (Keras)

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the Keras model
model_keras = keras.Sequential([
    # Input layer: size 2
    layers.Input(shape=(2,)),
    # Hidden layer: at least 2 neurons with ReLU or Tanh activation
    layers.Dense(units=4, activation='relu', name='hidden_layer'), # Using 4 neurons as an initial experiment
    # Output layer: 1 neuron with sigmoid activation for binary classification
    layers.Dense(units=1, activation='sigmoid', name='output_layer')
])

model_keras.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hidden_layer (Dense)            │ (None, 4)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17 (68.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

### Interpretation of MLP Architecture (Keras)

We've defined a simple Sequential Keras model for the XOR problem. It consists of:
*   An **input layer** that implicitly handles the 2 features of our `X` data.
*   A **hidden layer** with 4 neurons and a ReLU activation function. ReLU is a common choice for hidden layers due to its computational efficiency and ability to mitigate the vanishing gradient problem.
*   An **output layer** with a single neuron and a sigmoid activation function. Sigmoid is ideal for binary classification as it outputs a probability between 0 and 1.

## 3. Compile the Model (Keras)

In [3]:
# Compile the Keras model
model_keras.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("Keras model compiled successfully with Adam optimizer and Binary Cross-Entropy loss.")

Keras model compiled successfully with Adam optimizer and Binary Cross-Entropy loss.


### Interpretation of Model Compilation (Keras)

We compiled the Keras model with:
*   **Optimizer**: `'adam'`. Adam is an adaptive learning rate optimization algorithm that's widely used and generally performs well.
*   **Loss function**: `'binary_crossentropy'`. This is the standard loss function for binary classification problems where the output layer uses a sigmoid activation.
*   **Metrics**: We included `'accuracy'` to monitor the model's performance during training.

## 4. Train the Model (Keras)

In [4]:
# Train the Keras model
history_keras = model_keras.fit(X, y, epochs=1000, verbose=0) # Train for 1000 epochs, verbose=0 to suppress output per epoch

print("Keras model training complete.")

Keras model training complete.


### Interpretation of Model Training (Keras)

We trained the Keras model using the `fit` method with our `X` and `y` data. We set `epochs=1000` to allow the model sufficient iterations to learn the XOR pattern, which is a non-linear problem. `verbose=0` was used to prevent excessive output during training, showing only the final completion message. The training history is stored in `history_keras` which can be used for further analysis (e.g., plotting loss and accuracy).

## 5. Evaluate the Model (Keras)

In [5]:
# Predict outputs for all 4 input combinations using the trained Keras model
predictions_keras = model_keras.predict(X)

# Convert probabilities to binary output (0 or 1)
predicted_labels_keras = (predictions_keras > 0.5).astype(int)

print("Input (X):\n", X)
print("True Output (y):\n", y)
print("Predicted Output (Keras):\n", predicted_labels_keras)

# Check if the network correctly learns the XOR function
correct_predictions_keras = np.array_equal(y, predicted_labels_keras)
print(f"Keras model correctly learned the XOR function: {correct_predictions_keras}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
Input (X):
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
True Output (y):
 [[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output (Keras):
 [[0]
 [1]
 [1]
 [0]]
Keras model correctly learned the XOR function: True


### Interpretation of Model Evaluation (Keras)

We used the trained Keras model to `predict` the outputs for our original `X` inputs. Since the output layer uses a sigmoid activation, the predictions are probabilities between 0 and 1. We then converted these probabilities to binary labels (0 or 1) using a threshold of 0.5. Finally, we compared the predicted labels with the true `y` labels to determine if the model correctly learned the XOR function. A `True` result indicates successful learning.

## 6. Implement Using TensorFlow Low-Level API

Now, let's repeat the process using TensorFlow's low-level API to build and train the MLP for the XOR function.

### 2. Build an MLP (TensorFlow Low-Level API)

In [6]:
import tensorflow as tf

# Define the weights and biases for the hidden and output layers
# We will initialize them randomly

# Hidden layer parameters (2 inputs, 4 neurons)
W1 = tf.Variable(tf.random.normal([2, 4], dtype=tf.float32), name='W1')
b1 = tf.Variable(tf.zeros([4], dtype=tf.float32), name='b1')

# Output layer parameters (4 hidden neurons, 1 output neuron)
W2 = tf.Variable(tf.random.normal([4, 1], dtype=tf.float32), name='W2')
b2 = tf.Variable(tf.zeros([1], dtype=tf.float32), name='b2')

print("Weights and biases for TensorFlow low-level model initialized.")

Weights and biases for TensorFlow low-level model initialized.


### Interpretation of MLP Architecture (TensorFlow Low-Level API)

For the low-level TensorFlow implementation, we explicitly define the weights (`W`) and biases (`b`) for each layer as `tf.Variable` objects. These variables will be updated during training.
*   `W1` and `b1` correspond to the hidden layer, transforming the 2 input features into 4 hidden neuron activations.
*   `W2` and `b2` correspond to the output layer, transforming the 4 hidden activations into 1 output probability.

### Define Forward Pass, Loss, and Optimizer (TensorFlow Low-Level API)

In [7]:
# Define the forward pass
def forward_pass(X_input):
    # Hidden layer: X * W1 + b1, then apply ReLU activation
    hidden_output = tf.nn.relu(tf.matmul(X_input, W1) + b1)
    # Output layer: hidden_output * W2 + b2, then apply Sigmoid activation
    output = tf.nn.sigmoid(tf.matmul(hidden_output, W2) + b2)
    return output

# Define the binary cross-entropy loss function
def binary_crossentropy_loss(y_true, y_pred):
    return tf.reduce_mean(tf.keras.losses.binary_crossentropy(y_true, y_pred))

# Define the optimizer
optimizer = tf.optimizers.Adam(learning_rate=0.01)

print("Forward pass, loss function, and optimizer defined for TensorFlow low-level model.")

Forward pass, loss function, and optimizer defined for TensorFlow low-level model.


### Interpretation of Forward Pass, Loss, and Optimizer (TensorFlow Low-Level API)

*   **`forward_pass` function**: This function describes how the input `X_input` flows through the network. It calculates the hidden layer output using matrix multiplication (`tf.matmul`), adds the bias (`b1`), and applies the ReLU activation. Then, it does the same for the output layer, using `tf.nn.sigmoid` for binary classification.
*   **`binary_crossentropy_loss` function**: This custom loss function calculates the mean binary cross-entropy between the true labels (`y_true`) and the predicted probabilities (`y_pred`), mimicking the Keras implementation.
*   **Optimizer**: We use `tf.optimizers.Adam` with a learning rate of 0.01. This optimizer will adjust the weights and biases to minimize the loss during training.

### Train the Model (TensorFlow Low-Level API)

In [8]:
@tf.function
def train_step(X_batch, y_batch):
    with tf.GradientTape() as tape:
        y_pred = forward_pass(X_batch)
        loss = binary_crossentropy_loss(y_batch, y_pred)
    gradients = tape.gradient(loss, [W1, b1, W2, b2])
    optimizer.apply_gradients(zip(gradients, [W1, b1, W2, b2]))
    return loss

epochs_tf = 1000
for epoch in range(epochs_tf):
    loss_tf = train_step(X, y)
    # Optional: print loss every N epochs to monitor progress
    # if (epoch + 1) % 100 == 0:
    #     print(f"Epoch {epoch + 1}/{epochs_tf}, Loss: {loss_tf:.4f}")

print("TensorFlow low-level model training complete.")

TensorFlow low-level model training complete.


### Interpretation of Model Training (TensorFlow Low-Level API)

For the low-level TensorFlow training, we implemented a custom `train_step` function. This function uses `tf.GradientTape` to automatically compute the gradients of the loss with respect to our trainable variables (`W1, b1, W2, b2`). The Adam optimizer then applies these gradients to update the variables, minimizing the binary cross-entropy loss over 1000 epochs. The `@tf.function` decorator is used to compile the `train_step` into a callable TensorFlow graph, which can significantly improve performance.

### Evaluate the Model (TensorFlow Low-Level API)

In [9]:
# Predict outputs for all 4 input combinations using the trained TensorFlow low-level model
predictions_tf = forward_pass(X)

# Convert probabilities to binary output (0 or 1)
predicted_labels_tf = (predictions_tf > 0.5).numpy().astype(int)

print("Input (X):\n", X)
print("True Output (y):\n", y)
print("Predicted Output (TensorFlow Low-Level):\n", predicted_labels_tf)

# Check if the network correctly learns the XOR function
correct_predictions_tf = np.array_equal(y, predicted_labels_tf)
print(f"TensorFlow low-level model correctly learned the XOR function: {correct_predictions_tf}")

Input (X):
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
True Output (y):
 [[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output (TensorFlow Low-Level):
 [[0]
 [1]
 [1]
 [0]]
TensorFlow low-level model correctly learned the XOR function: True


### Interpretation of Model Evaluation (TensorFlow Low-Level API)

We used the `forward_pass` function, which represents our trained TensorFlow low-level model, to get predictions for the `X` inputs. Similar to the Keras model, these are probabilities, so we convert them to binary labels (0 or 1) using a 0.5 threshold and `numpy().astype(int)`.

Finally, we compare these `predicted_labels_tf` with the true `y` labels. A `True` result here confirms that our custom-built TensorFlow model, using low-level operations, has also successfully learned the non-linear XOR function.

## 6. Implement Using PyTorch

Now, let's repeat the process using PyTorch to build and train the MLP for the XOR function.

### 2. Build an MLP (PyTorch)

In [10]:
import torch
import torch.nn as nn
import torch.optim as optim

# Convert numpy arrays to PyTorch tensors
X_torch = torch.from_numpy(X)
y_torch = torch.from_numpy(y)

# Define the PyTorch model
class XOR_MLP_PyTorch(nn.Module):
    def __init__(self):
        super(XOR_MLP_PyTorch, self).__init__()
        # Hidden layer: 2 inputs, 4 neurons, ReLU activation
        self.hidden = nn.Linear(2, 4) # Input size 2, Output size 4
        self.relu = nn.ReLU()
        # Output layer: 4 hidden neurons, 1 output neuron, Sigmoid activation
        self.output = nn.Linear(4, 1) # Input size 4, Output size 1
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.hidden(x)
        x = self.relu(x)
        x = self.output(x)
        x = self.sigmoid(x)
        return x

model_pytorch = XOR_MLP_PyTorch()
print("PyTorch model created:")
print(model_pytorch)

PyTorch model created:
XOR_MLP_PyTorch(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (relu): ReLU()
  (output): Linear(in_features=4, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


### Interpretation of MLP Architecture (PyTorch)

For PyTorch, we define the MLP as a class inheriting from `nn.Module`.
*   The `__init__` method initializes the layers: a `nn.Linear` layer for the hidden layer (2 inputs, 4 outputs) followed by `nn.ReLU`, and another `nn.Linear` layer for the output (4 inputs, 1 output) followed by `nn.Sigmoid`.
*   The `forward` method defines the forward pass of the network, specifying how data flows through the layers. This structure closely mirrors our Keras and low-level TensorFlow implementations, maintaining 2 input neurons, a hidden layer with 4 neurons (ReLU), and an output neuron (sigmoid).

### 3. Compile the Model / Define Loss and Optimizer (PyTorch)

In [11]:
# Define the loss function (Binary Cross Entropy Loss) and optimizer (Adam)
loss_fn_pytorch = nn.BCELoss()
optimizer_pytorch = optim.Adam(model_pytorch.parameters(), lr=0.01)

print("PyTorch loss function (BCELoss) and optimizer (Adam) defined.")

PyTorch loss function (BCELoss) and optimizer (Adam) defined.


### 4. Train the Model (PyTorch)

In [12]:
# Train the PyTorch model
epochs_pytorch = 1000

for epoch in range(epochs_pytorch):
    # Forward pass
    y_pred_pytorch = model_pytorch(X_torch)

    # Calculate loss
    loss_pytorch = loss_fn_pytorch(y_pred_pytorch, y_torch)

    # Backward pass and optimize
    optimizer_pytorch.zero_grad() # Clear gradients
    loss_pytorch.backward()     # Compute gradients
    optimizer_pytorch.step()    # Update weights

    # Optional: print loss every N epochs
    # if (epoch + 1) % 100 == 0:
    #     print(f'Epoch [{epoch+1}/{epochs_pytorch}], Loss: {loss_pytorch.item():.4f}')

print("PyTorch model training complete.")

PyTorch model training complete.


### 5. Evaluate the Model (PyTorch)

In [13]:
# Predict outputs for all 4 input combinations using the trained PyTorch model
with torch.no_grad(): # Disable gradient calculation for inference
    predictions_pytorch = model_pytorch(X_torch)

# Convert probabilities to binary output (0 or 1)
# Detach from graph and convert to numpy for comparison
predicted_labels_pytorch = (predictions_pytorch > 0.5).int().numpy()

print("Input (X) in PyTorch tensor format:\n", X_torch.numpy())
print("True Output (y) in PyTorch tensor format:\n", y_torch.numpy())
print("Predicted Output (PyTorch):\n", predicted_labels_pytorch)

# Check if the network correctly learns the XOR function
correct_predictions_pytorch = np.array_equal(y_torch.numpy(), predicted_labels_pytorch)
print(f"PyTorch model correctly learned the XOR function: {correct_predictions_pytorch}")

Input (X) in PyTorch tensor format:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
True Output (y) in PyTorch tensor format:
 [[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output (PyTorch):
 [[0]
 [1]
 [1]
 [0]]
PyTorch model correctly learned the XOR function: True


### Interpretation of Model Evaluation (PyTorch)

Similar to the previous implementations, we used the trained PyTorch model to generate predictions for our input `X_torch`. The `torch.no_grad()` context manager ensures that gradients are not computed during inference, which is good practice for efficiency.

The `predictions_pytorch` are probabilities, so we convert them to binary labels (0 or 1) using a 0.5 threshold. Finally, we compare these predicted labels with the true `y_torch` labels. The result `PyTorch model correctly learned the XOR function: True` confirms that our PyTorch implementation is successful in solving the XOR problem.

## Summary and Conclusion

We have successfully implemented a Multi-Layer Perceptron (MLP) to learn the XOR Boolean function using three different deep learning frameworks:

1.  **Keras (TensorFlow high-level API):** Provided a concise and easy-to-use API for building, compiling, and training the model.
2.  **TensorFlow Low-Level API:** Demonstrated how to manually define weights, biases, forward pass, loss, and training steps, offering finer control over the model's operations.
3.  **PyTorch:** Showcased its object-oriented approach for defining models (`nn.Module`) and its explicit gradient computation during the training loop.

In all three cases, the MLP, despite its simplicity, was able to correctly learn the non-linear XOR function, achieving 100% accuracy on our small dataset. This highlights the power of neural networks to solve problems that are not linearly separable.

Feel free to ask if you'd like to explore further, perhaps by:
*   Changing hyperparameters (e.g., learning rate, number of neurons, activation functions).
*   Visualizing the decision boundary.
*   Adding more complex datasets.